server:
  port: 8080
  servlet:
    context-path: /tools
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tools?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
#  mapper-locations: classpath:mapper/*.xml
  mapper-locations: classpath*:com/sky/tools/dao/*.xml
  type-aliases-package: com.sky.tools.entity